---
### Download and unpack Go binaries
- name: Download step-certificates
  get_url:
    url: https://github.com/smallstep/certificates/releases/download/v{{ smallstep_version }}/step-certificates_linux_{{ smallstep_version }}_{{ smallstep_arch }}.tar.gz
    dest: /tmp/step-certificates.tar.gz
    mode: u=rwx,g=rx,o=rx
    force: true
- name: Download step-cli
  get_url:
    url: https://github.com/smallstep/cli/releases/download/v{{ smallstep_version }}/step-cli_linux_{{ smallstep_version }}_{{ smallstep_arch }}.tar.gz
    dest: /tmp/step-cli.tar.gz
    mode: u=rwx,g=rx,o=rx
    force: true
- name: Untar packages
  unarchive:
    src: "/tmp/{{ item }}"
    dest: /tmp
    remote_src: true
  loop:
    - step-scertificates.tar.gz
    - step-cli.tar.gz

### Make sure directories exist, and copy files into them
- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0775
  loop:
    - /usr/bin
    - /usr/lib/systemd/system
    - /usr/share/step-certificates/doc
    - /usr/share/step-cli/doc
  become: true
- name: Copy certificates binary files
  copy:
    src: "/tmp/step-certificates_{{ smallstep_version }}/bin/{{ item }}"
    dest: "/usr/bin/{{ item }}"
    remote_src: true
    owner: root
    group: root
    mode: 0775
  loop:
    - step-ca
    - step-cloudkms-init
  become: true
  notify: restart_ca_service
- name: Copy certificates README
  copy:
    src: /tmp/step-certificates_{{ smallstep_version }}/README.md
    dest: /usr/share/step-certificates/doc/README.md
    mode: 0664
  become: true
- name: Install systemd unit
  copy:
    src: step-ca.service
    dest: /usr/lib/systemd/system/step-ca.service
    owner: root
    group: root
    mode: 0664
  become: true
- name: Copy cli binary
  copy:
    src: /tmp/step-cli_{{ smallstep_version}}/bin/step
    dest: /usr/bin/step
    remote_src: true
    owner: root
    group: root
    mode: 0775
- name: Copy cli README
  copy:
    src: /tmp/step-cli_{{ smallstep_version }}/README.md
    dest: /usr/share/step-cli/doc/README.md
    mode: 0664
  become: true

### Create user, and assign permissions
- name: Add step group
  group: name=step
- name: Add step user
  user:
    name: step
    group: step
    home: /var/lib/step
    create_home: true

### Check for, and create config when needed
- name: Check for CA config
  stat:
    path: /var/lib/step/.step/config/ca.json
  register: ca_config

- block:
  ### Create password files
  - name: Get encyrption password
    set_fact:
      smallstep_encryption_password: "{{ lookup('password', '/var/lib/step/.password') }}"
  - name: Get provisioner password
    set_fact:
      smallstep_encryption_password: "{{ lookup('password', '/tmp/provisioner_password') }}"
  ### Initialize CA
  - name: Initialize CA
    command: step ca init --name=Smallstep --dns={{ ansible_fqdn }},localhost --address=127.0.0.1:8443 --provisioner=smallstep@{{ ansible_domain }} --provisioner-password-file=/tmp/provisioner_password --password-file=/var/lib/step/.password --with-ca-url=https://{{ ansible_fqdn }}
  - debug: msg="Provisioner password is stored in /tmp/provisioner_password. Please, move its contents to a password vault, and remove the file."

  when: not ca_config['stat']['exists']
