---
- name: Converge
  hosts: all

  vars:
    CacheInstances:
      - 'prd'

    EpicEnvironments:
      - {Instance: 'PRD', Environment: 'PRD'}

  pre_tasks:

  roles:
    - role: imntreal.smallstep-ca
