---
- name: Converge
  hosts: all
  gather_facts: false
  remote_user: root
  vars:
    cache_instances:
      - 'prd'

    epic_environments:
      - {Instance: 'PRD', Environment: 'PRD'}

  pre_tasks:

  roles:
    - role: imntreal.smallstep_ca
